{"body": "\nHi, guys,\n\nI don't know if you can kindly advise me on a Python related problem, or\nsuggest a source for help:\n\n1. the following gencumulativesky command runs OK in the terminal of Mac OS\nusing London's weather file:\n*GenCumulativeSky  +s1  -a 51.15  -o 0.18  -m -0.0 -h 0  -E  -time 0 24\n-date 1 1 12 31 ./London.epw > ./gcs_London.cal*\n\n... with two lines of error message:\n\n\n*There were 4586 sun up hours in this climate fileTotal Ibh/Lbh: 0.000000*\n\n2. But I can't get it working at all by running a Python script with the\nfollowing contents:\n\n\n*import oscmd = \"GenCumulativeSky  +s1  -a 51.15  -o 0.18  -m -0.0    -h 0\n-E  -time 0 24  -date 1 1 12 31 ./London.epw >\n./gcs_London.cal\"os.system(cmd)*\n\nThere is no error message in the Python IDLE, but the .cal file generated\nis zero ...\n\n\nMoreover, I got a lot more error messages when running the gencumulativesky\nprogram directly in the terminal of Mac OS X using Singapore's weather file:\n\nCommand:\n*GenCumulativeSky  +s1  -a 1.37  -o -103.98  -m -120.0    -h 0  -E  -time 0\n24  -date 1 1 12 31 ./SGP_Singapore.486980_IWEC.epw > ./gcs_SG.cal*\n\nErrors:\n\n\n\n\n*Error!  Solar altitude < 6 degrees and Idh > 10 W/m^2 on day 1!\nAttempting to continue!......Error!  Solar altitude < 6 degrees and Idh >\n10 W/m^2 on day 365!  Attempting to continue!There were 4354 sun up hours\nin this climate fileTotal Ibh/Lbh: 0.000000*\n\n\nThanks for your help!\n-------------- next part --------------\nAn HTML attachment was scrubbed...\nURL: <http://www.radiance-online.org/pipermail/radiance-general/attachments/20150219/da6ae0b9/attachment.html>\n\n", "replyTo": "", "sender": "Joe Smith", "isquestion": true, "tags": [], "id": "<CAGhWmF7R33E8d1O-gm6NfoqbiSAKNG9Yf9qkLLUYjH4ndh-sjg@mail.gmail.com>", "refs": [], "datetime": "Thu, 19 Feb 2015 11:32:41 +0800", "email": "the.oat.cracker at gmail.com", "subject": "[Radiance-general] problem of gencumulativesky driven through Python"}