{"body": "WARNING: At least one of the links in the message below goes to an .exe file, \nwhich could be malicious. To learn how to protect yourself, please go here:\nhttps://commons.lbl.gov/x/_591B\n\n\n\n\nHi Joe,\n\n\nI haven't automated gencumulativesky through Python, but I do a fair \namount of automation of Radiance commands using Python. I find that most \ncommands will not work unless you run the command with shell emulation \nenabled. I'm not familiar with os.system or os.popen, but this is an \nexample of my process using the subprocess module, and I hope it helps you.\n\n\n    import subprocess as sp\n\n\n    process = sp.Popen(['pcomb', '-e', '(expresssion)',\n    fullpath_hdr_fname, '|', 'pvalue', '-d', '-b', '-h', '-H', '>',\n    'tmp.txt'], *shell=True*)\n\n\n    process.wait()\n\n\n\n\nNote that the subprocess Popen command takes a list of individual \ncommand elements, and the shell=True portion is crucial.\n\n\n > /Moreover, I got a lot more error messages when running the \ngencumulativesky program directly in the terminal of Mac OS X using \nSingapore's weather file:/\nI am not sure where the 'official' gencumulative sky is available from \nthese days, but we noticed an issue way back in 2012 thanks to some \nsleuthing from Ji Zhang \n<http://diva4rhino.com/forum/topics/gencumulativesky-exe-problem>, and a \npatched version was issued. Unfortunately, I only have the Windows \nbinary of the fixed version, and the code is not open. A kind of dumb \nfix is to reverse your longitude input, as I believe the original \nversion had issues with areas in the eastern hemisphere.\n\n\nBest,\nAlstan\n___\n<sup>Automatically generated content from [radiance mailing-list](https://radiance-online.org/pipermail/radiance-general/2015-February/010751.html).</sup>", "attachments": [], "created_by_name": "Alstan Jakubiec", "created_at": "February 19, 2015 at 10:42PM", "created_by": "Alstan_Jakubiec", "parent_id": "radiance-general_010747", "id": "radiance-general_010751"}