{"body": "Hi Jan,\n\n\nThanks for the pointer. I've downloaded the pmap 4.3 version and tried\nto compile/install (after performing a fresh installation of radiance\n3.7), but the pmap installation is unsuccessful, with the following\nerror messages being generated by 'makeall install' during the\ncompilation:\n\n\n../lib/libpmap.a(pmapmat.o)(.text+0xf64): In function\n`anisoSpecPhotonScatter':\n: undefined reference to `getacoords'\n../lib/libpmap.a(pmapmat.o)(.text+0x1afb): In function\n`dielectricPhotonScatter' :\n: undefined reference to `mylog'\n../lib/libpmap.a(pmapmat.o)(.text+0x1b26): In function\n`dielectricPhotonScatter' :\n: undefined reference to `mylog'\n../lib/libpmap.a(pmapmat.o)(.text+0x1b51): In function\n`dielectricPhotonScatter' :\n: undefined reference to `mylog'\n../lib/libpmap.a(pmapmat.o)(.text+0x1db1): In function\n`dielectricPhotonScatter' :\n: undefined reference to `mylog'\n../lib/libpmap.a(pmapmat.o)(.text+0x1dd9): In function\n`dielectricPhotonScatter' :\n: undefined reference to `mylog'\n../lib/libpmap.a(pmapmat.o)(.text+0x1e01): more undefined references to\n`mylog' follow\ncollect2: ld returned 1 exit status\nmake: *** [mkpmap] Error 1\nmake: Target `install' not remade because of errors. ~/rad3R7/ray/src\n\n\nDo you have any idea of what might be causing this?\n\n\nThanks in advance,\n\n\nErico\n-----Original Message-----\n___\n<sup>Automatically generated content from [radiance mailing-list](https://radiance-online.org/pipermail/radiance-general/2006-January/003259.html).</sup>", "attachments": [], "created_by_name": "Erico Rosa", "created_at": "January 14, 2006 at 07:24PM", "created_by": "Erico_Rosa", "parent_id": "radiance-general_003254", "id": "radiance-general_003259"}